language: node_js
matrix:
  include:
  - node_js: '8'
    sudo: required
    os: linux
    dist: trusty
    addons:
      chrome: stable
    before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
    script: npm run test:integration

  - node_js: '8'
    sudo: required
    os: linux
    dist: trusty
    addons:
      chrome: stable
      firefox: latest
    before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    script:
    - npm run test:unit
